import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { CookieRecord, SameSiteMode } from '../types';
import { summarizeError } from '../utils/formatters';

interface Props { profileId?: string }
const sameSites: SameSiteMode[] = ['Strict', 'Lax', 'None', 'Unknown'];
const blank = (): Omit<CookieRecord, 'id' | 'profileId'> => ({ name: '', value: '', domain: '', path: '/', secure: true, httpOnly: true, sameSite: 'Lax', expiresAt: null });

export function CookieJarEditor({ profileId }: Props) {
  const [cookies, setCookies] = useState<Omit<CookieRecord, 'id' | 'profileId'>[]>([]);
  const [status, setStatus] = useState('');
  useEffect(() => { if (!profileId) return; api.getCookies(profileId).then(r => setCookies(r.cookies.map(({ name, value, domain, path, secure, httpOnly, sameSite, expiresAt }) => ({ name, value, domain, path, secure, httpOnly, sameSite, expiresAt })))).catch(e => setStatus(summarizeError(e))); }, [profileId]);
  if (!profileId) return null;
  function update(i: number, patch: Partial<Omit<CookieRecord, 'id' | 'profileId'>>) { setCookies(rows => rows.map((r, idx) => idx === i ? { ...r, ...patch } : r)); }
  async function save() { try { const r = await api.saveCookies(profileId, cookies.filter(c => c.name && c.domain)); setCookies(r.cookies.map(({ name, value, domain, path, secure, httpOnly, sameSite, expiresAt }) => ({ name, value, domain, path, secure, httpOnly, sameSite, expiresAt }))); setStatus('Cookie jar saved.'); } catch (e) { setStatus(summarizeError(e)); } }
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold text-white">Scoped cookie jar</h2><button className="rounded-lg bg-slate-800 px-3 py-2 text-sm" onClick={() => setCookies([...cookies, blank()])}>Add cookie</button></div><p className="mt-2 text-sm text-slate-400">Cookie values are sent to the backend for authorized replay only and are not stored by this frontend.</p><div className="mt-4 space-y-3">{cookies.map((c, i) => <div key={i} className="grid gap-2 rounded-xl border border-slate-800 p-3 md:grid-cols-6"><input aria-label="Cookie name" className="rounded-lg border border-slate-700 bg-slate-950 p-2" value={c.name} onChange={e => update(i, { name: e.target.value })} placeholder="name" /><input aria-label="Cookie value" className="rounded-lg border border-slate-700 bg-slate-950 p-2" value={c.value} onChange={e => update(i, { value: e.target.value })} placeholder="value" /><input aria-label="Cookie domain" className="rounded-lg border border-slate-700 bg-slate-950 p-2" value={c.domain} onChange={e => update(i, { domain: e.target.value })} placeholder="domain" /><input aria-label="Cookie path" className="rounded-lg border border-slate-700 bg-slate-950 p-2" value={c.path} onChange={e => update(i, { path: e.target.value })} /><select aria-label="SameSite" className="rounded-lg border border-slate-700 bg-slate-950 p-2" value={c.sameSite} onChange={e => update(i, { sameSite: e.target.value as SameSiteMode })}>{sameSites.map(s => <option key={s}>{s}</option>)}</select><button className="rounded-lg border border-red-400/40 px-3 py-2 text-sm text-red-200" onClick={() => setCookies(cookies.filter((_, idx) => idx !== i))}>Remove</button><label className="text-sm"><input type="checkbox" checked={c.secure} onChange={e => update(i, { secure: e.target.checked })} /> Secure</label><label className="text-sm"><input type="checkbox" checked={c.httpOnly} onChange={e => update(i, { httpOnly: e.target.checked })} /> HttpOnly</label></div>)}</div>{status && <p className="mt-3 text-sm text-cyan-100">{status}</p>}<button className="mt-4 rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950" onClick={save}>Save cookies</button></section>;
}
