import type { PreparedRequest } from '../types';
import { RequestPreviewCard } from './RequestPreviewCard';

interface Props { baseline?: PreparedRequest; variants: PreparedRequest[]; selectedIds: string[]; onSelectedIdsChange: (ids: string[]) => void; truncated?: boolean }

export function HeaderMatrix({ baseline, variants, selectedIds, onSelectedIdsChange, truncated }: Props) {
  const allIds = variants.map(v => v.requestId);
  function toggle(id: string) { onSelectedIdsChange(selectedIds.includes(id) ? selectedIds.filter(x => x !== id) : [...selectedIds, id]); }
  if (!baseline && !variants.length) return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 text-slate-300">Generate a preview to inspect baseline and mutated request variants.</div>;
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h2 className="text-lg font-semibold text-white">Generated request matrix</h2><div className="flex gap-2"><button className="rounded-lg bg-slate-800 px-3 py-2 text-sm" onClick={() => onSelectedIdsChange(allIds)}>Select all</button><button className="rounded-lg bg-slate-800 px-3 py-2 text-sm" onClick={() => onSelectedIdsChange([])}>Clear</button></div></div>{truncated && <p className="mt-3 rounded-lg bg-amber-500/10 p-3 text-sm text-amber-100">Backend policy truncated the preview to stay within run limits.</p>}{baseline && <div className="mt-4"><h3 className="mb-2 text-sm font-medium text-slate-300">Baseline</h3><RequestPreviewCard request={baseline} /></div>}<div className="mt-5 overflow-x-auto"><table className="min-w-full divide-y divide-slate-800 text-sm"><thead><tr className="text-left text-slate-400"><th className="px-3 py-2">Run</th><th className="px-3 py-2">Label</th><th className="px-3 py-2">Category</th><th className="px-3 py-2">Method</th><th className="px-3 py-2">URL</th><th className="px-3 py-2">Headers</th></tr></thead><tbody className="divide-y divide-slate-800">{variants.map(v => <tr key={v.requestId} className="text-slate-200"><td className="px-3 py-2"><input aria-label={`Select ${v.label}`} type="checkbox" checked={selectedIds.includes(v.requestId)} onChange={() => toggle(v.requestId)} /></td><td className="px-3 py-2 font-medium">{v.label}</td><td className="px-3 py-2">{v.category}</td><td className="px-3 py-2">{v.method}</td><td className="max-w-sm break-all px-3 py-2">{v.url}</td><td className="px-3 py-2">{v.headers.length}</td></tr>)}</tbody></table></div></section>;
}
