import type { MutationCategory } from '../types';

interface Props { available: string[]; selected: MutationCategory[]; onChange: (selected: MutationCategory[]) => void; allowCustom: boolean; customHeader: string; customValues: string; onCustomChange: (header: string, values: string) => void }
const labels: Record<string, string> = { host: 'Host', x_forwarded_for: 'X-Forwarded-For', x_forwarded_host: 'X-Forwarded-Host', x_forwarded_proto: 'X-Forwarded-Proto', x_original_url: 'X-Original-URL', x_rewrite_url: 'X-Rewrite-URL', origin: 'Origin', referer: 'Referer', method_override: 'Method override' };

export function MutationPresetPicker({ available, selected, onChange, allowCustom, customHeader, customValues, onCustomChange }: Props) {
  const usable = available.length ? available : Object.keys(labels);
  function toggle(cat: MutationCategory) { onChange(selected.includes(cat) ? selected.filter(c => c !== cat) : [...selected, cat]); }
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">Mutation categories</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{usable.map(cat => <label key={cat} className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-sm"><input type="checkbox" checked={selected.includes(cat as MutationCategory)} onChange={() => toggle(cat as MutationCategory)} /> <span>{labels[cat] || cat}</span></label>)}</div><div className="mt-5 rounded-xl border border-slate-800 p-4"><h3 className="font-medium text-white">Custom mutation</h3><p className="mt-1 text-sm text-slate-400">Available only when backend policy allows custom headers.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><input aria-label="Custom header name" disabled={!allowCustom} className="rounded-lg border border-slate-700 bg-slate-950 p-2 disabled:opacity-40" value={customHeader} onChange={e => onCustomChange(e.target.value, customValues)} placeholder="X-Test-Header" /><input aria-label="Custom values" disabled={!allowCustom} className="rounded-lg border border-slate-700 bg-slate-950 p-2 disabled:opacity-40" value={customValues} onChange={e => onCustomChange(customHeader, e.target.value)} placeholder="comma separated values" /></div></div></section>;
}
