import type { RunResult } from '../types';
import { formatMs } from '../utils/formatters';

interface Props { results: RunResult[]; selectedIds: string[]; onSelectionChange: (ids: string[]) => void }

export function ResponseDeltaTable({ results, selectedIds, onSelectionChange }: Props) {
  function toggle(id: string) { onSelectionChange(selectedIds.includes(id) ? selectedIds.filter(x => x !== id) : [...selectedIds, id]); }
  if (!results.length) return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 text-slate-300">No result records are available for this run yet.</div>;
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Response deltas</h2><button className="rounded-lg bg-slate-800 px-3 py-2 text-sm" onClick={() => onSelectionChange(results.map(r => r.resultId))}>Select all</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-full divide-y divide-slate-800 text-sm"><thead><tr className="text-left text-slate-400"><th className="px-3 py-2">Export</th><th className="px-3 py-2">Label</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Length</th><th className="px-3 py-2">Timing delta</th><th className="px-3 py-2">Header diffs</th><th className="px-3 py-2">Findings</th><th className="px-3 py-2">Error</th></tr></thead><tbody className="divide-y divide-slate-800">{results.map(r => <tr key={r.resultId} className="text-slate-200"><td className="px-3 py-2"><input aria-label={`Select ${r.label}`} type="checkbox" checked={selectedIds.includes(r.resultId)} onChange={() => toggle(r.resultId)} /></td><td className="px-3 py-2 font-medium">{r.label}<div className="text-xs text-slate-500">{r.category}</div></td><td className={`px-3 py-2 ${r.diffFromBaseline.statusChanged ? 'text-amber-200' : ''}`}>{r.response.status}</td><td className={`px-3 py-2 ${r.diffFromBaseline.lengthChanged ? 'text-amber-200' : ''}`}>{r.response.bodyLength}</td><td className="px-3 py-2">{formatMs(r.diffFromBaseline.timingDeltaMs)}</td><td className="px-3 py-2">{r.diffFromBaseline.headerDifferences.length}</td><td className="px-3 py-2">{r.findings.length}</td><td className="px-3 py-2 text-red-200">{r.error || '—'}</td></tr>)}</tbody></table></div></section>;
}
